In [3]:
# python libraries
# Numpy- Is a library for working with arrays od data.
# Scipy- Is a library of techniques for numerical and scientific computing.
# Matplotlib- Is a library for making visualizations.
# Seaborn- Is a higher- level interface to matplotlib visualization tasks. 

In [4]:
import numpy as np 
a = np.array([1, 2, 3]) # 3x1 numpy array
print(a, type(a))
print(a[0])
print(a.shape)

[1 2 3] <class 'numpy.ndarray'>
1
(3,)


In [5]:
b = np.array([[0.2, 2], [1.3, 1]])
print(b.shape)
print(b[0,0], b[0,1])

(2, 2)
0.2 2.0


In [6]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
c.shape

(3, 3)

In [7]:
c[1, 2]

6

In [8]:
d = np.sqrt(c)
d

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [9]:
# zeros array
e = np.zeros((3, 2))
e

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
# ones array
f = np.ones((2, 3))
f

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# full array with an integer
g = np.full((3, 3), 2.5)
g

array([[2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5]])

In [12]:
# random array 
h = np.random.random((2, 3))
h

array([[0.32653347, 0.39524694, 0.4651866 ],
       [0.67917127, 0.51399915, 0.96453124]])

In [18]:
# indexing array
i = np.array([[3, 1, 2, 1],
              [5, 1, 9, 5],
              [4, 9.1, 0, 7]])
j = i[:2, 1:3]
j

array([[1., 2.],
       [1., 9.]])

In [55]:
k = i[1:, 1:3]
k

array([[1. , 9. ],
       [9.1, 0. ]])

In [57]:
l = i[1:, 2:4]
l

array([[9., 5.],
       [0., 7.]])

In [76]:
m = i[1:, :2]
m

array([[5. , 1. ],
       [4. , 9.1]])